version: '3.3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 'sqlserver'
    container_name: sqlserver-restaurantreserves
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "AvS#a1s45s"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '11433:1433'    
    expose:
      - 1433
      
  restaurant.api:
    image: ${DOCKER_REGISTRY-}restaurantapi
    build:
      context: .
      dockerfile: restaurant-api/Restaurant.API/Dockerfile
    container_name: restaurantapi-restaurantreserves
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5015:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  webbff.api:
    image: ${DOCKER_REGISTRY-}webbffapi
    build:  
      context: .
      dockerfile: web-bff-api/WebBff.API/Dockerfile
    container_name: webbffapi-restaurantreserves
    depends_on:
      - restaurant.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5010:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
